### ISSUE TITLE
Profile Code

### ISSUE THREAD

**Issue by LukeShortCloud** [ekultails/card_games_converter#10]
From the [latest benchmarks](https://github.com/ekultails/card_games_converter/blob/22dd621e013691ea064094ca9be96804e055ceec/cgc_tdd.md#cache-benchmarking) it is shown that CGC 1.4.0 takes almost twice as long to process images than 1.3.0. This could be because of one of two reasons. Either

(1) The Pillow library CGC now uses is twice as slow as the previous implementation/usage of ImageMagick or
(2) During the refactoring there was additional code that processes images twice (probably unnecessarily, if at all).

CGC 1.3.0 and 1.4.0 should be profiled to compare the execution of each method. That will help pinpoint the profile. This issue especially needs to be addressed before adding multi-threading support for the upcoming 1.5.0 release.

"The first rule of any technology used in a business is that automation applied to an efficient operation will magnify the efficiency. The second is that automation applied to an inefficient operation will magnify the inefficiency." - Bill Gates

**Comment by LukeShortCloud** [comment]
It turns out that it is actually more than twice as fast (not as slow). These are the results that I was expecting in the first place. This now means one of a few things could have affected the tests:

* A recent minor Fedora update
    * Possibly Linux kernel related
* Accidentally installing CGC under Python 2 instead of 3 (we do not support Python 2, although it technically will work under 2)

Moving forward, I will re-test against the same environment (possibly standardize it by using a standardized Vagrant box pinned to a specific version) and update the technical design document with the new results.

# cProfile Test Results

Cumulative method time with 100 images and no cache.

Command: `echo 3 | sudo tee /proc/sys/vm/drop_caches && sync && python3 -m cProfile -s time ~/.local/bin/cgc-cli.py --cache none >> /tmp/profile_${CGC_VERSION}.txt`

| Method | 1.3.1 | 1.4.0 |
| --- | --- | --- |
| find_first_image | 0.000 | 0.000 |
| image_info | 0.046 | 0.032 |
| calc_ppi | 0.000 | 0.000 |
| {convert,image}_rotate | 8.735 | 2.981 |
| {convert,image}_rotate_by_dimensions | 8.766 | 3.086 |
| convert_image_density/image_density_change | 9.891 | 5.394 |
| {convert,images}_merge | 16.873 | 5.697 |
| convert_single | 18.660 | 8.595 |
| convert_batch_directory | 18.679 | 8.614 |
| convert_batch_append | 16.873 | 5.852 |
| convert_batch_append_all | 35.553 | 14.466 |

**Comment by LukeShortCloud** [comment]
Back to square one, the performance issues are happening all over again.

I know from the last set of tests I triple checked the version output and that, along with the slightly different function names, helped me correctly distinguish the test results. Sometimes the new version is twice as fast and sometimes it's twice as slow. Right now, it's twice as slow again.

-----

# Cache Benchmarking

Benchmark hardware:

* Processor: Intel i7-8750H
* RAM: x2 16GB 2400MHz DDR4
* Storage: NVMe

Benchmark software:

* Fedora 28 docker container

## CGC 1.3.0

Python 3.6.6, ImageMagick 6.9.9.38

| Description | Cache Type | Real Time |
| ----------- | ---------- | --------- |
| 100 cards | none | 0m41.442s |
| 100 cards | name | 0m17.027s |
| 100 cards | sha512 | 0m19.021s |

## CGC 1.4.0

Python 3.6.6, Pillow 5.4.0

| Description | Cache Type | Real Time |
| ----------- | ---------- | --------- |
| 100 cards | none | 1m17.621s |
| 100 cards | name | 0m36.618s |
| 100 cards | sha512 | 0m36.954s |

**Comment by LukeShortCloud** [comment]
CGC actually will not even run on Python 2 at all because memory pointers aren't supported.

```
# time cgc-cli.py
Traceback (most recent call last):
  File "/usr/bin/cgc-cli.py", line 5, in <module>
    from cgc.cgc import CGC
  File "/usr/lib/python2.7/site-packages/cgc/cgc.py", line 314
    cmd = ["convert", convert_merge_arg, *image_paths,
```

This rules out the possibility of accidentally installing to Python 2 vs Python 3.

**Comment by LukeShortCloud** [comment]
Moving forward, I will continue to work on adding multi-threading support and leave this open.

I am assuming that Pillow is twice as slow (as it is this way more often than not) which is fine considering the benefits of (A) avoiding running shell commands and (B) makes CGC cross-platform. Further profiling/benchmarking with future versions  of CGC can be done via the use of a single thread.

**Comment by LukeShortCloud** [comment]
Multithreading has been added to help offset the penalty of using Pillow. We also have benchmarks listed for every release. Closing as resolved.
